/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SendLetterRouteImport } from './routes/send-letter'
import { Route as MyLettersRouteImport } from './routes/my-letters'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminNisRouteImport } from './routes/admin.nis'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminKamusRouteImport } from './routes/admin.kamus'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'

const SendLetterRoute = SendLetterRouteImport.update({
  id: '/send-letter',
  path: '/send-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLettersRoute = MyLettersRouteImport.update({
  id: '/my-letters',
  path: '/my-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNisRoute = AdminNisRouteImport.update({
  id: '/nis',
  path: '/nis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKamusRoute = AdminKamusRouteImport.update({
  id: '/kamus',
  path: '/kamus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/my-letters': typeof MyLettersRoute
  '/send-letter': typeof SendLetterRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/kamus': typeof AdminKamusRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/nis': typeof AdminNisRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-letters': typeof MyLettersRoute
  '/send-letter': typeof SendLetterRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/kamus': typeof AdminKamusRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/nis': typeof AdminNisRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/my-letters': typeof MyLettersRoute
  '/send-letter': typeof SendLetterRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/kamus': typeof AdminKamusRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/nis': typeof AdminNisRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/my-letters'
    | '/send-letter'
    | '/admin/inbox'
    | '/admin/kamus'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/nis'
    | '/admin/students'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-letters'
    | '/send-letter'
    | '/admin/inbox'
    | '/admin/kamus'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/nis'
    | '/admin/students'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/my-letters'
    | '/send-letter'
    | '/admin/inbox'
    | '/admin/kamus'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/nis'
    | '/admin/students'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MyLettersRoute: typeof MyLettersRoute
  SendLetterRoute: typeof SendLetterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/send-letter': {
      id: '/send-letter'
      path: '/send-letter'
      fullPath: '/send-letter'
      preLoaderRoute: typeof SendLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-letters': {
      id: '/my-letters'
      path: '/my-letters'
      fullPath: '/my-letters'
      preLoaderRoute: typeof MyLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nis': {
      id: '/admin/nis'
      path: '/nis'
      fullPath: '/admin/nis'
      preLoaderRoute: typeof AdminNisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kamus': {
      id: '/admin/kamus'
      path: '/kamus'
      fullPath: '/admin/kamus'
      preLoaderRoute: typeof AdminKamusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInboxRoute: typeof AdminInboxRoute
  AdminKamusRoute: typeof AdminKamusRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNisRoute: typeof AdminNisRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInboxRoute: AdminInboxRoute,
  AdminKamusRoute: AdminKamusRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNisRoute: AdminNisRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MyLettersRoute: MyLettersRoute,
  SendLetterRoute: SendLetterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
