/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SendLetterRouteImport } from './routes/send-letter'
import { Route as MyLettersRouteImport } from './routes/my-letters'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentSendLetterRouteImport } from './routes/student.send-letter'
import { Route as StudentRepositoryRouteImport } from './routes/student.repository'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStudentProfilesRouteImport } from './routes/admin.student-profiles'
import { Route as AdminRepositoryRouteImport } from './routes/admin.repository'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNisRouteImport } from './routes/admin.nis'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminKamusRouteImport } from './routes/admin.kamus'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminGuruReportRouteImport } from './routes/admin.guru-report'
import { Route as AdminCounselingRouteImport } from './routes/admin.counseling'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterRoute = SendLetterRouteImport.update({
  id: '/send-letter',
  path: '/send-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLettersRoute = MyLettersRouteImport.update({
  id: '/my-letters',
  path: '/my-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentSendLetterRoute = StudentSendLetterRouteImport.update({
  id: '/send-letter',
  path: '/send-letter',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRepositoryRoute = StudentRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentProfilesRoute = AdminStudentProfilesRouteImport.update({
  id: '/student-profiles',
  path: '/student-profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRepositoryRoute = AdminRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNisRoute = AdminNisRouteImport.update({
  id: '/nis',
  path: '/nis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKamusRoute = AdminKamusRouteImport.update({
  id: '/kamus',
  path: '/kamus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuruReportRoute = AdminGuruReportRouteImport.update({
  id: '/guru-report',
  path: '/guru-report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCounselingRoute = AdminCounselingRouteImport.update({
  id: '/counseling',
  path: '/counseling',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/my-letters': typeof MyLettersRoute
  '/send-letter': typeof SendLetterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/counseling': typeof AdminCounselingRoute
  '/admin/guru-report': typeof AdminGuruReportRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/kamus': typeof AdminKamusRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/nis': typeof AdminNisRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/repository': typeof AdminRepositoryRoute
  '/admin/student-profiles': typeof AdminStudentProfilesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/repository': typeof StudentRepositoryRoute
  '/student/send-letter': typeof StudentSendLetterRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-letters': typeof MyLettersRoute
  '/send-letter': typeof SendLetterRoute
  '/admin/counseling': typeof AdminCounselingRoute
  '/admin/guru-report': typeof AdminGuruReportRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/kamus': typeof AdminKamusRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/nis': typeof AdminNisRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/repository': typeof AdminRepositoryRoute
  '/admin/student-profiles': typeof AdminStudentProfilesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/repository': typeof StudentRepositoryRoute
  '/student/send-letter': typeof StudentSendLetterRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/my-letters': typeof MyLettersRoute
  '/send-letter': typeof SendLetterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/counseling': typeof AdminCounselingRoute
  '/admin/guru-report': typeof AdminGuruReportRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/kamus': typeof AdminKamusRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/nis': typeof AdminNisRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/repository': typeof AdminRepositoryRoute
  '/admin/student-profiles': typeof AdminStudentProfilesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/repository': typeof StudentRepositoryRoute
  '/student/send-letter': typeof StudentSendLetterRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/my-letters'
    | '/send-letter'
    | '/student'
    | '/admin/counseling'
    | '/admin/guru-report'
    | '/admin/inbox'
    | '/admin/kamus'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/nis'
    | '/admin/reports'
    | '/admin/repository'
    | '/admin/student-profiles'
    | '/admin/students'
    | '/admin/users'
    | '/student/repository'
    | '/student/send-letter'
    | '/admin/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-letters'
    | '/send-letter'
    | '/admin/counseling'
    | '/admin/guru-report'
    | '/admin/inbox'
    | '/admin/kamus'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/nis'
    | '/admin/reports'
    | '/admin/repository'
    | '/admin/student-profiles'
    | '/admin/students'
    | '/admin/users'
    | '/student/repository'
    | '/student/send-letter'
    | '/admin'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/my-letters'
    | '/send-letter'
    | '/student'
    | '/admin/counseling'
    | '/admin/guru-report'
    | '/admin/inbox'
    | '/admin/kamus'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/nis'
    | '/admin/reports'
    | '/admin/repository'
    | '/admin/student-profiles'
    | '/admin/students'
    | '/admin/users'
    | '/student/repository'
    | '/student/send-letter'
    | '/admin/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MyLettersRoute: typeof MyLettersRoute
  SendLetterRoute: typeof SendLetterRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter': {
      id: '/send-letter'
      path: '/send-letter'
      fullPath: '/send-letter'
      preLoaderRoute: typeof SendLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-letters': {
      id: '/my-letters'
      path: '/my-letters'
      fullPath: '/my-letters'
      preLoaderRoute: typeof MyLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/send-letter': {
      id: '/student/send-letter'
      path: '/send-letter'
      fullPath: '/student/send-letter'
      preLoaderRoute: typeof StudentSendLetterRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/repository': {
      id: '/student/repository'
      path: '/repository'
      fullPath: '/student/repository'
      preLoaderRoute: typeof StudentRepositoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/student-profiles': {
      id: '/admin/student-profiles'
      path: '/student-profiles'
      fullPath: '/admin/student-profiles'
      preLoaderRoute: typeof AdminStudentProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/repository': {
      id: '/admin/repository'
      path: '/repository'
      fullPath: '/admin/repository'
      preLoaderRoute: typeof AdminRepositoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nis': {
      id: '/admin/nis'
      path: '/nis'
      fullPath: '/admin/nis'
      preLoaderRoute: typeof AdminNisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kamus': {
      id: '/admin/kamus'
      path: '/kamus'
      fullPath: '/admin/kamus'
      preLoaderRoute: typeof AdminKamusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guru-report': {
      id: '/admin/guru-report'
      path: '/guru-report'
      fullPath: '/admin/guru-report'
      preLoaderRoute: typeof AdminGuruReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/counseling': {
      id: '/admin/counseling'
      path: '/counseling'
      fullPath: '/admin/counseling'
      preLoaderRoute: typeof AdminCounselingRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCounselingRoute: typeof AdminCounselingRoute
  AdminGuruReportRoute: typeof AdminGuruReportRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminKamusRoute: typeof AdminKamusRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNisRoute: typeof AdminNisRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRepositoryRoute: typeof AdminRepositoryRoute
  AdminStudentProfilesRoute: typeof AdminStudentProfilesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCounselingRoute: AdminCounselingRoute,
  AdminGuruReportRoute: AdminGuruReportRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminKamusRoute: AdminKamusRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNisRoute: AdminNisRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRepositoryRoute: AdminRepositoryRoute,
  AdminStudentProfilesRoute: AdminStudentProfilesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentRepositoryRoute: typeof StudentRepositoryRoute
  StudentSendLetterRoute: typeof StudentSendLetterRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentRepositoryRoute: StudentRepositoryRoute,
  StudentSendLetterRoute: StudentSendLetterRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MyLettersRoute: MyLettersRoute,
  SendLetterRoute: SendLetterRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
