declare module "@/routeTree.gen" {
  // This module is generated by @tanstack/router-plugin when running dev/build.
  // The declaration keeps editor/type tooling stable before first generation.
  export const routeTree: unknown;
}

